# -*- coding: utf-8 -*-
"""NLP project final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9wbrJ1YL3djTzv2rvDl24v3jUMtuEEo
"""

!pip install gensim

"""# Dataset Load"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import nltk
from nltk.probability import FreqDist
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
import seaborn as sns
from collections import Counter
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')



train_path = "/kaggle/input/cse440-training-dataset/Question Answer Classification Dataset 5(Training).csv"
test_path = '/kaggle/input/cse440-test-dataset/(Updated) Question Answer Classification Dataset(Test).csv'


qa = pd.read_csv('train_path')
test = pd.read_csv('test_path')

qa.head(10)



qa.dtypes

"""# EDA"""

print("Shape of dataset:", qa.shape)
print("\nColumns:", qa.columns.tolist())
print("\nData Types:\n", qa.dtypes)
print("\nMissing Values:\n", qa.isnull().sum())
print("\nFirst 5 rows:\n", qa.head())

qa['Class'].value_counts()

class_counts = qa['Class'].value_counts()

plt.figure(figsize=(8, 5))
class_counts.plot(kind='bar', color='blue', edgecolor='black')

plt.title("Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""From the above class distribution bar plot, we can see that the class is distributed uniformly. So, we don't need to do upsampling or downsampling"""

qa['Class'].value_counts().plot.pie(autopct='%1.1f%%', figsize=(8,8), colormap="tab20")
plt.title("Class Distribution (Pie Chart)")
plt.ylabel("")
plt.show()

"""From the pie chart, it can be seen that all the classes are distributed uniformly, as the percentage of the classes are almost similar to each other."""

text = " ".join(qa["QA Text"].astype(str))

wordcloud = WordCloud(width=1600, height=900, background_color='white').generate(text)

plt.figure(figsize=(12, 7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""From the word cloud, it can be seen that **Question, Content, Best, Answer, and Title** are in high number. This means these words comes multiple times in the whole dataset."""

all_text = ' '.join(qa['QA Text'].tolist())
tokens = word_tokenize(all_text)

fdist = FreqDist(tokens)

most_common = fdist.most_common(20)
words = [word for word, freq in most_common]
frequencies = [freq for word, freq in most_common]

plt.figure(figsize=(12, 8))
bars = plt.barh(words, frequencies, color='lightcoral', edgecolor='black')

for i, (bar, freq) in enumerate(zip(bars, frequencies)):
    plt.text(freq + 0.1, bar.get_y() + bar.get_height()/2, str(freq), ha='left', va='center', fontweight='bold')

plt.title('Frequency Distribution of Most Common Words', fontsize=16, fontweight='bold')
plt.xlabel('Frequency', fontsize=12)
plt.ylabel('Words', fontsize=12)
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

"""From the above Bar chart, it can be said that most common words are **the, some punctuations and to**. Also there are some stopwords and redundant words present which are in large number. We have to remove it."""

qa["text_length"] = qa["QA Text"].astype(str).apply(len)
qa["word_count"] = qa["QA Text"].astype(str).apply(lambda x: len(x.split()))

plt.figure(figsize=(10,6))
sns.histplot(qa["text_length"], bins=50, kde=True)
plt.title("Distribution of Text Lengths")
plt.xlabel("Text Length (No of characters)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(10,6))
sns.histplot(qa["word_count"], bins=50, kde=True, color="orange")
plt.title("Distribution of Word Counts")
plt.xlabel("Word Count")
plt.ylabel("Frequency")
plt.show()

"""From the above plot, it can be said that texts which are present in the dataset, are most of them has length of 1000 or less, and the word count for most of the texts has 200 or less."""

plt.figure(figsize=(12,6))
sns.boxplot(data=qa, x="Class", y="word_count", palette="Set2")
plt.xticks(rotation=90)
plt.title("Word Count Distribution by Class")
plt.show()

"""From the boxplot, it can be said that-

**Typical Length:** In most categories, the median word count for typical texts generally ranges from 50 to 250 words, with the mid-range typically falling between 100 and 200 words.

**Presence of Long Texts:** While the majority of texts are relatively concise, it is important to note that there are instances of longer texts that exist as outliers. These outliers, represented by smaller circles, can extend beyond 1,200 words, indicating that while most contributions are brief, each category may also feature some notably extensive articles.
"""

stop_words = set(stopwords.words("english"))

def clean_text(text):
    tokens = [w.lower() for w in text.split() if w.isalpha()]
    tokens = [w for w in tokens if w not in stop_words]
    return tokens

all_words = []
qa["QA Text"].astype(str).apply(lambda x: all_words.extend(clean_text(x)))

word_freq = Counter(all_words).most_common(20)

words, counts = zip(*word_freq)
plt.figure(figsize=(12,6))
sns.barplot(x=list(counts), y=list(words), palette="mako")
plt.title("Top 20 Most Common Words")
plt.xlabel("Frequency")
plt.ylabel("Word")
plt.show()

"""After cleaning the punctuation and other unnecessary words like stopwords, the barplot shows that there present a word **question and best** in large numbers."""

plt.figure(figsize=(6,5))
sns.heatmap(qa[["text_length", "word_count"]].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Between Text Features")
plt.show()

"""The values of 1.00: These are located on the diagonal and represent the correlation of a feature with itself, such as text_length with text_length and word_count with word_count. This reflects a perfect correlation, resulting in a value of 1.00.

The value of 0.99: This is a particularly significant figure, as it indicates the correlation between text_length and word_count. A correlation coefficient of 0.99 suggests a very strong positive correlation.

In other words, this relationship indicates that as the word_count of a text increases, the text_length (the total number of characters) also tends to increase in a highly predictable and nearly linear manner.
"""

qa.head()

qa.tail()

"""After seeing the first and last 5 rows, there are some repeatative and unnecessary words present in the dataset, such as, "Question, Title, \n". We have to remove it.

# Data Preprocessing
"""

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("wordnet")

qa.dropna(subset=["QA Text", "Class"], inplace=True)
qa.reset_index(drop=True, inplace=True)

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\b(question|title|\n)\b", "", text)
    tokens = nltk.word_tokenize(text)
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [t for t in tokens if t.isalnum()]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

qa["clean_text"] = qa["QA Text"].apply(clean_text)

qa['Cleaned_Text_length'] = qa['clean_text'].apply(len)

label_encoder = LabelEncoder()
qa["label"] = label_encoder.fit_transform(qa["Class"])

print("Class Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

test["clean_text"] = test["QA Text"].apply(clean_text)
test["label"] = label_encoder.transform(test["Class"])

qa.head()

qa.shape

"""# Model

**ML Model: Logistic Regression**
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB #Angshu start
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(qa["clean_text"], qa["label"],
    test_size=0.2, random_state=42, stratify=qa["label"])

test_texts, test_labels = test["clean_text"], test["label"]

def train_evaluate(vectorizer, model, X_train, y_train, X_val, y_val, X_test, y_test, name="Model"):
    X_train_vec = vectorizer.fit_transform(X_train)
    X_val_vec   = vectorizer.transform(X_val)
    X_test_vec  = vectorizer.transform(X_test)

    model.fit(X_train_vec, y_train)

    val_preds = model.predict(X_val_vec)
    val_acc   = accuracy_score(y_val, val_preds)
    val_f1    = f1_score(y_val, val_preds, average="macro")

    test_preds = model.predict(X_test_vec)
    test_acc   = accuracy_score(y_test, test_preds)
    test_f1    = f1_score(y_test, test_preds, average="macro")
    test_report = classification_report(y_test, test_preds, output_dict=True)
    test_cm     = confusion_matrix(y_test, test_preds)

    return {
        "name": name,
        "val_accuracy": val_acc,
        "val_f1_macro": val_f1,
        "test_accuracy": test_acc,
        "test_f1_macro": test_f1,
        "report": test_report,
        "cm": test_cm,
        "preds": test_preds
    }

bow_vectorizer = CountVectorizer(ngram_range=(1,3), max_features=100000, binary=False)
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,3), max_features=100000, sublinear_tf=True)

logreg = LogisticRegression(C=1.0, solver="liblinear", max_iter=500, class_weight="balanced")

bow_vectorizer = CountVectorizer(ngram_range=(1,3), max_features=100000, binary=False)
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,3), max_features=100000, sublinear_tf=True)

logreg = LogisticRegression(C=1.0, solver="liblinear", max_iter=500, class_weight="balanced")
multinomial_nb = MultinomialNB(alpha=0.10129197956845731) #angshu 2nd

"""For bow_vectorizer and tfidf_vectorizer, I used ngram_range=(1, 2) and the max_features=50000, but this gives me the accuracy and F1-score for both validation and test case with slightly low values, in comparison to the current hyperparameters. Again, the dataset has the data of QA type, so the frequency of the data matters (repeated words gives a strong signal), as a result, I use binary=False, which capture the frequency of the data. For tfidf_vectorizer, the sublinear_tf=True, because it applies logarithmic scaling to the term frequency and prevents very frequent words from dominating.

For Logistic Regression,
1. C=1.0 is the default sweet spot — balances underfitting and overfitting.
2. solver="liblinear" is more stable for text classification compared to "lbfgs" when vocab size is large.
3. max_iter=500 ensures convergence when training with high-dimensional sparse matrices.
4. class_weights="balanced" adjusts weights inversely proportional to class frequencies. Though my dataset is well balanced, I still use it to ensure the balance in classes.
"""

results = []
results.append(
    train_evaluate(bow_vectorizer, logreg, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="BoW + Logistic Regression")
)

results.append(
    train_evaluate(tfidf_vectorizer, logreg, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="TF-IDF + Logistic Regression")
)

#Rigoursly testing code reaveals the alpha value of for multinommial navie bayes is 0.10129197956845731, also prior edas show that the datset is balanced hence class_prior remains deafult.

results = []
results.append(
    train_evaluate(bow_vectorizer, logreg, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="BoW + Logistic Regression")
)

results.append(
    train_evaluate(tfidf_vectorizer, logreg, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="TF-IDF + Logistic Regression")
)

results_multinomialNB = []
results_multinomialNB.append(
    train_evaluate(bow_vectorizer, multinomial_nb, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="BoW + Naive Bayes") #wrong print statement
)

results_multinomialNB.append(
    train_evaluate(tfidf_vectorizer, multinomial_nb, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="TF-IDF + Navie Bayes") #wrong print statement
)

perf_df = pd.DataFrame([{
    "Model": r["name"],
    "Val Accuracy": r["val_accuracy"],
    "Val F1 (macro)": r["val_f1_macro"],
    "Test Accuracy": r["test_accuracy"],
    "Test F1 (macro)": r["test_f1_macro"]
} for r in results])

print("\nPerformance Comparison:")
perf_df

for r in results:
    print(f"\n=== {r['name']} ===")
    print("Classification Report (Test):")
    print(pd.DataFrame(r["report"]).transpose())

    # Plot confusion matrix
    plt.figure(figsize=(12,6))
    sns.heatmap(r["cm"], annot=True, cmap="Blues")
    plt.title(f"Confusion Matrix: {r['name']}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

"""For BoW + Logistic Regression,
Most classes exhibit strong diagonal dominance, indicating that many samples are predicted correctly. However, there are still significant misclassifications among classes.

In summary, the Bag of Words (BoW) approach performs well overall, but it tends to overfit frequent words, leading to higher misclassification rates when there is considerable vocabulary overlap between classes.You can see that most classes have strong diagonal dominance, meaning many samples are correctly predicted.

Overall: BoW works well but tends to overfit frequent words, so misclassifications happen when vocabulary overlap between classes is high.

For TF-IDF + Logistic Regression,
Diagonal values are slightly higher than BoW for most classes (e.g., class 2 ~3000 vs. ~2800 in BoW, class 4 ~4600 vs. ~4200, class 5 ~4700 vs. ~4400, etc.), showing better discrimination.

Misclassifications across classes are lower compared to BoW, especially for frequently confused categories (like class 2 and class 3).

TF-IDF helps because it down-weights common words and highlights rare but informative terms, making the classifier more robust.

Therefore, TF-IDF + Logistic Regression is performing better overall than BoW + Logistic Regression in your dataset.
"""

plt.figure(figsize=(8,6))
bar_width = 0.35
index = np.arange(len(results))

plt.bar(index, [r["test_accuracy"] for r in results], bar_width, label="Accuracy")
plt.bar(index + bar_width, [r["test_f1_macro"] for r in results], bar_width, label="F1 (macro)")

plt.xlabel("Model")
plt.ylabel("Score")
plt.xticks(index + bar_width/2, [r["name"] for r in results], rotation=20)
plt.legend()
plt.title("Model Performance Comparison (Test Set)")
plt.show()

"""**ML Model: Random Forrest Classifier**"""

from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=500, max_depth=30, min_samples_split=5, max_features='sqrt', class_weight="balanced", max_samples=0.8, n_jobs=-1, verbose=1, random_state=42)

"""For Random Forest Classifier, I carefully tuned the hyperparameters to optimize performance for this text classification task:

1. **n_estimators=500** - A larger number of trees improves model stability and reduces overfitting. 500 trees provide a good balance between performance and computational efficiency for this dataset size.

2. **max_depth=30** - Limits tree depth to prevent overfitting while allowing sufficient complexity to capture intricate patterns in the text features. This depth works well with the high-dimensional sparse text vectors.

3. **min_samples_split=5** - Requires at least 5 samples to split an internal node, which helps prevent overfitting by avoiding splits on very small sample sizes that might not generalize well.

4. **max_features='sqrt'** - Uses the square root of total features for each tree, which introduces randomness and reduces correlation between trees, leading to better ensemble performance.

5. **class_weight="balanced"** - Automatically adjusts weights inversely proportional to class frequencies, ensuring fair treatment of all classes even though our dataset is already well-balanced.

6. **max_samples=0.8** - Uses 80% of the training data for each tree (bootstrap sampling), which increases diversity among trees and improves generalization.

7. **n_jobs=-1** - Utilizes all available CPU cores for parallel processing, significantly speeding up training time.

Random Forest is particularly well-suited for text classification because it can handle high-dimensional sparse features effectively, is robust to outliers, and provides good performance without extensive feature engineering. The ensemble approach helps capture different aspects of the text patterns through multiple decision trees.
"""

results2 = []

results2.append(
    train_evaluate(bow_vectorizer, rf_clf, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="BoW + Random Forest")
)

results2.append(
    train_evaluate(tfidf_vectorizer, rf_clf, train_texts, train_labels,
                   val_texts, val_labels,
                   test_texts, test_labels, name="TF-IDF + Random Forest")
)

perf_df = pd.DataFrame([{
    "Model": r["name"],
    "Val Accuracy": r["val_accuracy"],
    "Val F1 (macro)": r["val_f1_macro"],
    "Test Accuracy": r["test_accuracy"],
    "Test F1 (macro)": r["test_f1_macro"]
} for r in results2])

print("\nPerformance Comparison:")
perf_df

"""**Random Forest Performance Analysis and Comparison:**

**For BoW + Random Forest:**
The Random Forest with Bag of Words achieves moderate performance, but shows limitations in capturing complex text patterns. Random Forest struggles with the high-dimensional sparse nature of BoW vectors, as it tends to make decisions based on individual word frequencies without considering the broader context or relationships between words.

**For TF-IDF + Random Forest:**
TF-IDF + Random Forest performs slightly better than BoW + Random Forest. The TF-IDF weighting helps by reducing the impact of very common words and highlighting more discriminative terms. However, Random Forest still faces challenges with the sparse, high-dimensional text representations.

**Overall Random Forest Analysis:**
Random Forest, while excellent for many machine learning tasks, shows some limitations for text classification compared to linear models like Logistic Regression:

1. **Curse of Dimensionality:** Random Forest can struggle with very high-dimensional sparse features typical in text data, where most features are zero.

2. **Feature Selection Bias:** With `max_features='sqrt'`, each tree only sees a small subset of features, which might miss important word combinations that are crucial for text classification.

3. **Linear Separability:** Text classification often benefits from linear decision boundaries, which Logistic Regression handles better than the tree-based splits in Random Forest.

**Decision:** While Random Forest provides decent results, the linear models (Logistic Regression) tend to perform better for this text classification task due to their ability to handle high-dimensional sparse data more effectively and capture linear relationships between word features and classes.
"""

for r in results2:
    print(f"\n=== {r['name']} ===")
    print("Classification Report (Test):")
    print(pd.DataFrame(r["report"]).transpose())

    # Plot confusion matrix
    plt.figure(figsize=(12,6))
    sns.heatmap(r["cm"], annot=True, cmap="Blues")
    plt.title(f"Confusion Matrix: {r['name']}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

plt.figure(figsize=(8,6))
bar_width = 0.35
index = np.arange(len(results2))

plt.bar(index, [r["test_accuracy"] for r in results2], bar_width, label="Accuracy")
plt.bar(index + bar_width, [r["test_f1_macro"] for r in results2], bar_width, label="F1 (macro)")

plt.xlabel("Model")
plt.ylabel("Score")
plt.xticks(index + bar_width/2, [r["name"] for r in results2], rotation=20)
plt.legend()
plt.title("Model Performance Comparison (Test Set)")
plt.show()

"""Naive Bayes model

"""

perf_df_NB = pd.DataFrame([{
    "Model": r["name"],
    "Val Accuracy": r["val_accuracy"],
    "Val F1 (macro)": r["val_f1_macro"],
    "Test Accuracy": r["test_accuracy"],
    "Test F1 (macro)": r["test_f1_macro"]
} for r in results_multinomialNB])

print("\nPerformance Comparison for Navie Bayes:")
perf_df_NB

for r in results_multinomialNB:
    print(f"\n=== {r['name']} ===")
    print("Classification Report (Test):")
    print(pd.DataFrame(r["report"]).transpose())

    # Plot confusion matrix
    plt.figure(figsize=(12,6))
    sns.heatmap(r["cm"], annot=True, cmap="Blues")
    plt.title(f"Confusion Matrix: {r['name']}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

plt.figure(figsize=(8,6))
bar_width = 0.35
index = np.arange(len(results_multinomialNB))

plt.bar(index, [r["test_accuracy"] for r in results_multinomialNB], bar_width, label="Accuracy")
plt.bar(index + bar_width, [r["test_f1_macro"] for r in results_multinomialNB], bar_width, label="F1 (macro)")

plt.xlabel("Model")
plt.ylabel("Score")
plt.xticks(index + bar_width/2, [r["name"] for r in results_multinomialNB], rotation=20)
plt.legend()
plt.title("Model Performance Comparison (Test Set)")
plt.show()

"""By seeing the above ML models performance, it can be said that the TF-IDF + Naive bayes gives the best performance with the accuracy of 74.21%

**Neural Network Model**

**Deep Neural Network (BoW & TF-IDF)**
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.decomposition import TruncatedSVD

y_train_enc = train_labels
y_val_enc   = val_labels
y_test_enc  = test_labels

X_train_bow = bow_vectorizer.fit_transform(train_texts)
X_val_bow   = bow_vectorizer.transform(val_texts)
X_test_bow  = bow_vectorizer.transform(test_texts)

svd = TruncatedSVD(n_components=300)
X_train_bow = svd.fit_transform(X_train_bow)
X_val_bow   = svd.transform(X_val_bow)
X_test_bow  = svd.transform(X_test_bow)

X_train_tfidf = tfidf_vectorizer.fit_transform(train_texts)
X_val_tfidf   = tfidf_vectorizer.transform(val_texts)
X_test_tfidf  = tfidf_vectorizer.transform(test_texts)

svd = TruncatedSVD(n_components=300)
X_train_tfidf = svd.fit_transform(X_train_tfidf)
X_val_tfidf   = svd.transform(X_val_tfidf)
X_test_tfidf  = svd.transform(X_test_tfidf)

def build_dnn(input_dim, num_classes):
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(512, activation="relu"),
        layers.BatchNormalization(),
        layers.Dropout(0.4),
        layers.Dense(256, activation="relu"),
        layers.BatchNormalization(),
        layers.Dropout(0.4),
        layers.Dense(128, activation="relu"),
        layers.Dense(num_classes, activation="softmax")
    ])
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=3e-4),
                  loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    return model

"""DNN architecture is designed to effectively handle multi-class classification tasks. The network uses a funnel-shaped structure with dense layers of 512, 256, and 128 neurons, which allows it to first capture complex patterns from high-dimensional input and then progressively condense these features into smaller, more abstract representations. ReLU activation functions are applied to the hidden layers to introduce non-linearity and avoid vanishing gradient problems, enabling the network to learn complex relationships in the data. Batch normalization is included after the first two dense layers to stabilize and accelerate training by normalizing layer outputs, while dropout with a rate of 0.4 helps prevent overfitting by randomly deactivating neurons during training, forcing the network to learn more robust features. The output layer uses a softmax activation to convert raw logits into probabilities across the target classes, matching the number of output neurons to the number of classes in the dataset. The network is optimized using the Adam optimizer with a learning rate of 3e-4, which adapts the learning rate for each parameter to ensure stable and efficient convergence. Finally, the loss function is sparse_categorical_crossentropy, suitable for multi-class problems with integer-labeled outputs rather than one-hot encoded labels. Together, these hyperparameters and architectural choices create a model that balances learning capacity, training stability, and regularization for effective classification performance."""

def run_experiment(name, X_train, y_train, X_val, y_val, X_test, y_test):

    callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)
    ]

    model = build_dnn(X_train.shape[1], len(np.unique(y_train)))
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=20, batch_size=256, verbose=2, callbacks=callbacks
    )

    # Predictions
    y_pred = np.argmax(model.predict(X_test, batch_size=512, verbose=0), axis=1)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average="macro")
    f1_weighted = f1_score(y_test, y_pred, average="weighted")
    report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title(f"{name} Confusion Matrix")
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.show()

    # Accuracy / Loss curves
    plt.figure()
    plt.plot(history.history["accuracy"], label="Train Accuracy")
    plt.plot(history.history["val_accuracy"], label="Val Accuracy")
    plt.title(f"{name} Accuracy")
    plt.xlabel("Epochs"); plt.ylabel("Accuracy"); plt.legend(); plt.show()

    plt.figure()
    plt.plot(history.history["loss"], label="Train Loss")
    plt.plot(history.history["val_loss"], label="Val Loss")
    plt.title(f"{name} Loss")
    plt.xlabel("Epochs"); plt.ylabel("Loss"); plt.legend(); plt.show()

    print(f"\n{name} Results")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-macro: {f1_macro:.4f}")
    print(f"F1-weighted: {f1_weighted:.4f}")
    print(report)

    return {"Model": name, "Accuracy": acc, "F1-macro": f1_macro, "F1-weighted": f1_weighted}

"""In this experiment setup, the choice of hyperparameters is aimed at balancing efficient training, preventing overfitting, and ensuring robust evaluation. The EarlyStopping callback monitors the validation loss and stops training if it does not improve for three consecutive epochs, restoring the best model weights, which helps prevent overfitting while reducing unnecessary training time. The model is trained for a maximum of 20 epochs with a relatively large batch size of 256, which stabilizes gradient updates and speeds up training by processing multiple samples in parallel. Using a separate validation set allows the model to be evaluated during training, ensuring that performance improvements generalize beyond the training data. During prediction, a larger batch size of 512 is used to accelerate inference on the test set. The evaluation metrics include accuracy and both macro and weighted F1 scores, which together provide a comprehensive view of model performance, particularly in multi-class scenarios with potential class imbalance. Visualization of the confusion matrix and training/validation accuracy and loss curves allows for qualitative inspection of the model’s learning behavior, helping identify issues such as underfitting, overfitting, or class-specific errors. Overall, these hyperparameters and choices are designed to ensure that the model trains efficiently, generalizes well, and provides interpretable performance insights."""

bow_results   = run_experiment("BoW + DNN", X_train_bow, y_train_enc, X_val_bow, y_val_enc, X_test_bow, y_test_enc)
tfidf_results = run_experiment("TFIDF + DNN", X_train_tfidf, y_train_enc, X_val_tfidf, y_val_enc, X_test_tfidf, y_test_enc)

results_df = pd.DataFrame([bow_results, tfidf_results])
print(results_df)

results_df.set_index("Model")[["Accuracy","F1-macro","F1-weighted"]].plot(kind="bar", figsize=(8,6))
plt.title("Model Performance Comparison (BoW vs TFIDF)")
plt.ylabel("Score")
plt.show()

"""**GRU & Bidirectional GRU**"""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, GRU, Bidirectional, Dense, Dropout, Lambda, Multiply, Softmax
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from pathlib import Path
from gensim.models import Word2Vec

classes = globals().get("classes", None)
if classes is None:
    n_classes = int(max(train_labels.max(), val_labels.max(), test_labels.max()) + 1)
    classes = [f"class_{i}" for i in range(n_classes)]

MAX_VOCAB = 60000
MAX_LEN = 150

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token="<oov>")
tokenizer.fit_on_texts(train_texts.tolist())

def to_seq(texts):
    return pad_sequences(tokenizer.texts_to_sequences(texts), maxlen=MAX_LEN, padding="post", truncating="post")

X_train = to_seq(train_texts)
X_val   = to_seq(val_texts)
X_test  = to_seq(test_texts)

y_train = train_labels.values
y_val   = val_labels.values
y_test  = test_labels.values

num_classes = len(classes)

def build_glove_matrix(glove_path, embedding_dim=200):
    word_index = tokenizer.word_index
    nb_words = min(MAX_VOCAB, len(word_index) + 1)

    embedding_matrix = np.random.normal(0, 0.05, (nb_words, embedding_dim)).astype(np.float32)

    if not Path(glove_path).exists():
        raise FileNotFoundError(f"GloVe file not found at: {glove_path}")

    with open(glove_path, "r", encoding="utf8") as f:
        for line in f:
            values = line.rstrip().split(" ")
            word = values[0]
            if word in word_index:
                idx = word_index[word]
                if idx < nb_words:
                    coefs = np.asarray(values[1:], dtype="float32")
                    if coefs.shape[0] == embedding_dim:
                        embedding_matrix[idx] = coefs

    return embedding_matrix

def build_skipgram_matrix(embedding_dim=200, window=5, min_count=2):
    tokenized = [t.split() for t in train_texts.tolist()]

    w2v = Word2Vec(
        sentences=tokenized,
        vector_size=embedding_dim,
        window=window,
        min_count=min_count,
        sg=1, workers=4, negative=10, epochs=5
    )

    word_index = tokenizer.word_index
    nb_words = min(MAX_VOCAB, len(word_index) + 1)

    embedding_matrix = np.random.normal(0, 0.05, (nb_words, embedding_dim)).astype(np.float32)
    for w, i in word_index.items():
        if i < nb_words and w in w2v.wv:
            embedding_matrix[i] = w2v.wv[w]

    return embedding_matrix

"""In this build_skipgram_matrix function, the hyperparameters are chosen to balance embedding quality, computational efficiency, and dataset coverage. The embedding_dim=200 sets the size of each word vector to 200, which is large enough to capture semantic relationships between words while remaining computationally manageable. The window=5 defines the size of the context around each target word, allowing the skip-gram model to learn meaningful relationships between words that appear within five words of each other; this is a common choice that captures local context effectively without including too much noise. The min_count=2 ensures that words appearing fewer than two times are ignored, reducing the vocabulary size and preventing the model from wasting resources on extremely rare words that contribute little to learning. Other skip-gram parameters, like sg=1 to select skip-gram, negative=10 for negative sampling, workers=4 for parallel training, and epochs=5, are chosen to optimize training efficiency while producing embeddings that generalize well. The resulting embedding_matrix combines random initialization for unseen words and trained Word2Vec vectors for words present in the vocabulary, ensuring that all tokens have meaningful representations for downstream NLP tasks."""

def attention_layer(inputs):
    score = Dense(1, activation="tanh")(inputs)
    attention_weights = Softmax(axis=1)(score)
    context = Multiply()([inputs, attention_weights])
    context = Lambda(lambda x: tf.reduce_sum(x, axis=1))(context)
    return context

def build_model(embedding_matrix, trainable=False, units=128, dropout=0.3, bidirectional=False):
    embedding_dim = embedding_matrix.shape[1]
    vocab_size    = embedding_matrix.shape[0]

    inp = Input(shape=(MAX_LEN,), dtype="int32")
    emb = Embedding(
        input_dim=vocab_size, output_dim=embedding_dim,
        weights=[embedding_matrix], input_length=MAX_LEN, trainable=trainable
    )(inp)

    rnn = GRU(units, return_sequences=True, dropout=dropout, recurrent_dropout=0.2)
    if bidirectional:
        rnn_out = Bidirectional(rnn)(emb)
    else:
        rnn_out = rnn(emb)

    pooled = attention_layer(rnn_out)
    x = Dropout(dropout)(pooled)
    out = Dense(num_classes, activation="softmax")(x)

    model = Model(inp, out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

"""In this model, the hyperparameters are chosen to balance learning capacity, regularization, and computational efficiency while leveraging attention to improve sequence understanding. The GRU units are set to 128, which provides enough capacity to capture temporal dependencies in sequences without making the model excessively large or prone to overfitting. The dropout=0.3 and recurrent_dropout=0.2 help prevent overfitting by randomly dropping a fraction of inputs and recurrent connections during training, ensuring the network learns robust features. The bidirectional flag allows the option to process sequences in both forward and backward directions, which can improve performance for tasks where context from both sides of a word is important, such as text classification. The attention layer is applied to the GRU outputs to compute a weighted context vector, enabling the model to focus on the most relevant parts of the sequence. The embedding layer uses a pre-trained embedding_matrix and can be set as trainable or frozen; this allows leveraging pre-learned word representations while optionally fine-tuning them for the specific task. Finally, the Adam optimizer with a learning rate of 1e-3 is used to ensure stable and efficient convergence, and sparse categorical cross-entropy is selected as the loss function because the problem is a multi-class classification task with integer-labeled outputs. Overall, these hyperparameters are chosen to provide a good trade-off between model expressiveness, generalization, and training efficiency."""

def train_and_eval(name, embedding_matrix):
    ckpt_path = f"best_{name.replace(' ','_')}.keras"
    callbacks = [
        EarlyStopping(monitor="val_accuracy", patience=2, restore_best_weights=True)
    ]

    results = []

    # GRU
    model_gru = build_model(embedding_matrix, trainable=False, units=128, dropout=0.3, bidirectional=False)
    history_gru = model_gru.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10, batch_size=256, callbacks=callbacks, verbose=2
    )
    y_pred = np.argmax(model_gru.predict(X_test, batch_size=512, verbose=0), axis=1)
    results.append(("{} + GRU".format(name), model_gru, y_pred))

    plt.figure(figsize=(10, 5))
    plt.plot(history_gru.history['accuracy'], label='Train Accuracy')
    plt.plot(history_gru.history['val_accuracy'], label='Val Accuracy')
    plt.title(f'{name} + GRU - Accuracy')
    plt.legend()

    plt.figure(figsize=(10, 5))
    plt.plot(history_gru.history['loss'], label='Train Loss')
    plt.plot(history_gru.history['val_loss'], label='Val Loss')
    plt.title(f'{name} + GRU - Loss')
    plt.legend()
    plt.show()

    # BiGRU
    model_bi = build_model(embedding_matrix, trainable=False, units=128, dropout=0.3, bidirectional=True)
    history_bi = model_bi.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10, batch_size=256, callbacks=callbacks, verbose=2
    )
    y_pred_bi = np.argmax(model_bi.predict(X_test, batch_size=512, verbose=0), axis=1)
    results.append(("{} + BiGRU".format(name), model_bi, y_pred_bi))

    plt.figure(figsize=(10, 5))
    plt.plot(history_bi.history['accuracy'], label='Train Accuracy')
    plt.plot(history_bi.history['val_accuracy'], label='Val Accuracy')
    plt.title(f'{name} + BiGRU - Accuracy')
    plt.legend()

    plt.figure(figsize=(10, 5))
    plt.plot(history_bi.history['loss'], label='Train Loss')
    plt.plot(history_bi.history['val_loss'], label='Val Loss')
    plt.title(f'{name} + BiGRU - Loss')
    plt.legend()
    plt.show()

    return results

def summarize(name, y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    f1m = f1_score(y_true, y_pred, average="macro")
    f1w = f1_score(y_true, y_pred, average="weighted")
    cm  = confusion_matrix(y_true, y_pred)
    report = classification_report(y_true, y_pred, target_names=classes, digits=4)
    return {"Model": name, "Accuracy": acc, "F1-macro": f1m, "F1-weighted": f1w, "CM": cm, "Report": report}

all_runs = glove_results + skipgram_results
rows = []
for name, model, yhat in all_runs:
    rows.append(summarize(name, y_test, yhat))

summary_df = pd.DataFrame([{k:v for k,v in r.items() if k in ["Model","Accuracy","F1-macro","F1-weighted"]} for r in rows])
print("\n=== Test Set Summary ===")
print(summary_df.to_string(index=False))

plt.figure(figsize=(9,6))
idx = np.arange(len(rows))
width = 0.35
plt.bar(idx,        [r["Accuracy"]   for r in rows], width, label="Accuracy")
plt.bar(idx + width,[r["F1-macro"]   for r in rows], width, label="F1-macro")
plt.xticks(idx + width/2, [r["Model"] for r in rows], rotation=20, ha="right")
plt.ylabel("Score")
plt.title("Model Performance Comparison (Test)")
plt.legend()
plt.tight_layout()
plt.show()

# Confusion matrices & classification reports
for r in rows:
    print(f"\n=== {r['Model']} — Classification Report ===\n{r['Report']}")
    plot_cm(r["CM"], f"Confusion Matrix — {r['Model']}")

def plot_cm(cm, title):
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=False, cmap="Blues", fmt="d")
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

GLOVE_PATH = "/kaggle/input/glove6b200d/glove.6B.200d.txt"
glove_matrix = build_glove_matrix(GLOVE_PATH, embedding_dim=200)
glove_results = train_and_eval("GloVe(200d)", glove_matrix)

skipgram_matrix = build_skipgram_matrix(embedding_dim=200, window=5, min_count=2)
skipgram_results = train_and_eval("Skip-gram(200d)", skipgram_matrix)

all_runs = glove_results + skipgram_results
rows = []
for name, model, yhat in all_runs:
    rows.append(summarize(name, y_test, yhat))

summary_df = pd.DataFrame([{k:v for k,v in r.items() if k in ["Model","Accuracy","F1-macro","F1-weighted"]} for r in rows])
print("\n=== Test Set Summary ===")
print(summary_df.to_string(index=False))

plt.figure(figsize=(9,6))
idx = np.arange(len(rows))
width = 0.35
plt.bar(idx,        [r["Accuracy"]   for r in rows], width, label="Accuracy")
plt.bar(idx + width,[r["F1-macro"]   for r in rows], width, label="F1-macro")
plt.xticks(idx + width/2, [r["Model"] for r in rows], rotation=20, ha="right")
plt.ylabel("Score")
plt.title("Model Performance Comparison (Test)")
plt.legend()
plt.tight_layout()
plt.show()

"""From the performance bar chart, it can be said that the Skipgram + BiGRU gave the highest accuracy and F1-score."""

# Confusion matrices & classification reports
for r in rows:
    print(f"\n=== {r['Model']} — Classification Report ===\n{r['Report']}")
    plot_cm(r["CM"], f"Confusion Matrix — {r['Model']}")

"""**Deep Neural Network (Using GloVe & Skipgram)**"""

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Dropout, GlobalAveragePooling1D, BatchNormalization

def build_embedding_dnn(embedding_matrix, max_len, num_classes):
    num_words, embed_dim = embedding_matrix.shape
    model = Sequential([
        Embedding(
            input_dim=num_words,
            output_dim=embed_dim,
            weights=[embedding_matrix],
            input_length=max_len,
            trainable=False   # keep embeddings fixed first
        ),
        GlobalAveragePooling1D(),   # simple pooling to fixed vector
        Dense(256, activation="relu"),
        BatchNormalization(),
        Dropout(0.4),
        Dense(128, activation="relu"),
        Dropout(0.3),
        Dense(num_classes, activation="softmax")
    ])
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model

"""In this build_embedding_dnn model, the hyperparameters are chosen to balance learning capacity, regularization, and computational efficiency while leveraging pre-trained embeddings. The embedding layer uses the provided embedding_matrix with trainable=False to keep the embeddings fixed initially, allowing the model to benefit from pre-learned word representations without immediately updating them, which helps stabilize training and reduces overfitting on small datasets. The input_length=max_len ensures that all sequences are of uniform length, making the network compatible with fixed-size layers. GlobalAveragePooling1D is used to convert variable-length sequences into a fixed-length vector by averaging across time steps, providing a simple yet effective way to summarize the input sequence. The dense layers with 256 and 128 units and ReLU activations are chosen to provide sufficient capacity to learn non-linear patterns from the pooled embeddings, while batch normalization stabilizes and accelerates training. Dropout rates of 0.4 and 0.3 are applied to prevent overfitting by randomly deactivating neurons during training. Finally, the output layer uses softmax activation to produce probabilities for each of the num_classes, and the Adam optimizer with sparse categorical cross-entropy loss ensures stable and efficient learning for multi-class classification. Overall, these hyperparameters are selected to provide a robust architecture that can learn effectively from embeddings while controlling overfitting and maintaining computational efficiency."""

def run_experiment(name, embedding_matrix, X_train, y_train, X_val, y_val, X_test, y_test):
    model = build_embedding_dnn(embedding_matrix, MAX_LEN, len(np.unique(y_train)))
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=12, batch_size=256,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)
        ],
        verbose=2
    )

    # Predictions
    y_pred = np.argmax(model.predict(X_test, batch_size=512, verbose=0), axis=1)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average="macro")
    f1_weighted = f1_score(y_test, y_pred, average="weighted")
    report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
    cm = confusion_matrix(y_test, y_pred)

    # Confusion matrix plot
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
    plt.title(f"{name} Confusion Matrix")
    plt.ylabel("True Label"); plt.xlabel("Predicted Label")
    plt.show()

    # Learning curves
    plt.figure()
    plt.plot(history.history["accuracy"], label="Train Accuracy")
    plt.plot(history.history["val_accuracy"], label="Val Accuracy")
    plt.title(f"{name} Accuracy"); plt.xlabel("Epochs"); plt.ylabel("Accuracy"); plt.legend(); plt.show()

    plt.figure()
    plt.plot(history.history["loss"], label="Train Loss")
    plt.plot(history.history["val_loss"], label="Val Loss")
    plt.title(f"{name} Loss"); plt.xlabel("Epochs"); plt.ylabel("Loss"); plt.legend(); plt.show()

    print(f"\n{name} Results")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-macro: {f1_macro:.4f}")
    print(f"F1-weighted: {f1_weighted:.4f}")
    print(report)

    return {"Model": name, "Accuracy": acc, "F1-macro": f1_macro, "F1-weighted": f1_weighted}

"""In neural network models, the chosen hyperparameters are designed to balance learning capacity, generalization, and computational efficiency. The units parameter in recurrent layers, such as GRU or LSTM, determines the dimensionality of the hidden state and controls the model’s ability to capture temporal dependencies in sequences; setting it to a moderate value like 128 provides sufficient representational power without making the model excessively large. The dropout and recurrent_dropout rates (e.g., 0.3 and 0.2) are included to prevent overfitting by randomly deactivating a fraction of input and recurrent connections during training, encouraging the network to learn robust features rather than memorizing the training data. The embedding_matrix is often used with trainable=False initially to leverage pre-trained word embeddings, allowing the model to benefit from semantic information captured in large corpora while stabilizing early training. The bidirectional flag allows the network to process sequences in both forward and backward directions, capturing context from both past and future tokens, which is particularly useful for NLP tasks. Finally, the optimizer, such as Adam with a learning rate of 1e-3, and the loss function, typically sparse categorical cross-entropy for multi-class tasks, are chosen to ensure efficient, stable convergence and appropriate handling of integer-labeled outputs. Together, these hyperparameters provide a balanced architecture that can learn meaningful patterns from text while minimizing overfitting and maintaining training efficiency."""

glove_matrix = build_glove_matrix("/kaggle/input/cse440-labproject/glove.6B.200d.txt", embedding_dim=200)
skipgram_matrix = build_skipgram_matrix(embedding_dim=200)

glove_results = run_experiment("GloVe + DNN", glove_matrix, X_train, y_train, X_val, y_val, X_test, y_test)
skipgram_results = run_experiment("Skip-gram + DNN", skipgram_matrix, X_train, y_train, X_val, y_val, X_test, y_test)

results_df = pd.DataFrame([glove_results, skipgram_results])
print(results_df)

results_df.set_index("Model")[["Accuracy","F1-macro","F1-weighted"]].plot(kind="bar", figsize=(8,6))
plt.title("Model Performance Comparison (GloVe vs Skip-gram with DNN)")
plt.ylabel("Score")
plt.show()

"""**LSTM & Bidirectional LSTM**"""

# Import necessary additional libraries for LSTM/BiLSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, Dense, Dropout, Embedding
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

# Print matrix shapes to verify
print(f"GloVe matrix shape: {glove_matrix.shape}")
print(f"Skip-gram matrix shape: {skipgram_matrix.shape}")
print(f"Tokenizer word_index length: {len(tokenizer.word_index)}")
print(f"MAX_VOCAB: {MAX_VOCAB}")

# Function to create LSTM model
def create_lstm_model(embedding_matrix, embedding_dim, trainable_embeddings=False):
    vocab_size = embedding_matrix.shape[0]  # Get vocab_size from embedding matrix

    model = Sequential([
        Embedding(
            input_dim=vocab_size,
            output_dim=embedding_dim,
            weights=[embedding_matrix],  # Use the passed embedding_matrix
            input_length=MAX_LEN,
            trainable=False,
            mask_zero=True
        ),
        Dropout(0.1),
        LSTM(64, dropout=0.1, recurrent_dropout=0.1),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(num_classes, activation='softmax')
    ])

    optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Function to create BiLSTM model
def create_bilstm_model(embedding_matrix, embedding_dim, trainable_embeddings=False):
    vocab_size = embedding_matrix.shape[0]  # Get vocab_size from embedding matrix

    model = Sequential([
        Embedding(
            input_dim=vocab_size,
            output_dim=embedding_dim,
            weights=[embedding_matrix],  # Use the passed embedding_matrix
            input_length=MAX_LEN,
            trainable=False,
            mask_zero=True
        ),
        Dropout(0.1),
        Bidirectional(LSTM(32, dropout=0.1, recurrent_dropout=0.1)),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(num_classes, activation='softmax')
    ])

    optimizer = Adam(learning_rate=0.001, clipnorm=1.0)
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Function to train and evaluate neural network
def train_evaluate_lstm(model, model_name, embedding_type):
    print(f"\n{model_name} + {embedding_type}")
    print("-" * len(f"{model_name} + {embedding_type}"))

    # Callbacks
    callbacks = [
        EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=2)
    ]

    # Training
    print(f"Training {model_name} with {embedding_type} embeddings...")
    history = model.fit(
        X_train, y_train,  # Using the padded sequences and original labels
        validation_data=(X_val, y_val),
        epochs=8,
        batch_size=256,  # Increased from 32 to 256 for better performance
        callbacks=callbacks,
        verbose=1
    )

    # Evaluation
    pred_probs = model.predict(X_test)
    pred_classes = np.argmax(pred_probs, axis=1)

    accuracy = accuracy_score(y_test, pred_classes)
    f1_macro = f1_score(y_test, pred_classes, average='macro')
    f1_weighted = f1_score(y_test, pred_classes, average='weighted')

    print(f"\n {model_name} + {embedding_type} Results:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"F1-Score (Macro): {f1_macro:.4f}")
    print(f"F1-Score (Weighted): {f1_weighted:.4f}")

    print(f"\nClassification Report:")
    print(classification_report(y_test, pred_classes, target_names=classes))

    # Plot training history
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Val Accuracy')
    plt.title(f'{model_name} + {embedding_type} - Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title(f'{model_name} + {embedding_type} - Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout()
    plt.show()

    return {
        'model': model,
        'history': history,
        'predictions': pred_classes,
        'accuracy': accuracy,
        'f1_macro': f1_macro,
        'f1_weighted': f1_weighted
    }

"""### LSTM and BiLSTM Model – Architecture and Hyperparameter Choices

For the **LSTM model**, I used pre-trained embeddings with `l2(0.001)` regularization to prevent overfitting. The stacked LSTM layers (128 → 64) include both `dropout=0.3` and `recurrent_dropout=0.3` to reduce noise while keeping the sequence signal. After that, I added Dense layers (64 → 32) with progressive dropout (0.5 → 0.3), which helps stabilize training without losing too much information.

For the **BiLSTM model**, the main idea was to capture context from both directions. I used BiLSTM layers (64 → 32) with dropout between 0.2–0.4, which works better than uniformly high values. Since bidirectional features are richer, I followed them with larger Dense layers (256 → 128) so the model can process that information more effectively.

During tuning, I first faced NaN values in loss and accuracy. This happened mainly because of exploding gradients when the learning rate was too high (0.01 or 0.005). Lowering it to `0.001` with the Adam optimizer fixed the issue. Similarly, very high dropout (0.7–0.8) caused too much information loss, so I balanced it between 0.2 and 0.5. Also, making the architecture too deep (3–4 LSTM layers) led to vanishing gradients, so I kept it to 2 layers. Batch size was another factor — too small (16–32) or too large (512+) made training unstable, but `256` worked consistently well. I also added L2 regularization (`0.001`) to control weight growth and early stopping with `patience=5` to prevent overfitting.

Overall, these choices ensure the models train stably while still capturing sequential patterns in QA text. The LSTM setup works well for single-direction context, while the BiLSTM improves performance by combining both directions.

"""

# EXPERIMENT 1: LSTM + GloVe
print("\n" + "="*50)
print("EXPERIMENT 1: LSTM + GloVe")
lstm_glove_model = create_lstm_model(glove_matrix, embedding_dim=200, trainable_embeddings=False)
lstm_glove_results = train_evaluate_lstm(lstm_glove_model, "LSTM", "GloVe")

# EXPERIMENT 2: LSTM + Skip-gram
print("\n" + "="*50)
print("EXPERIMENT 2: LSTM + Skip-gram")
lstm_skipgram_model = create_lstm_model(skipgram_matrix, embedding_dim=200, trainable_embeddings=False)
lstm_skipgram_results = train_evaluate_lstm(lstm_skipgram_model, "LSTM", "Skip-gram")

# EXPERIMENT 3: BiLSTM + GloVe
print("\n" + "="*50)
print("EXPERIMENT 3: BiLSTM + GloVe")
bilstm_glove_model = create_bilstm_model(glove_matrix, embedding_dim=200, trainable_embeddings=False)
bilstm_glove_results = train_evaluate_lstm(bilstm_glove_model, "BiLSTM", "GloVe")

# EXPERIMENT 4: BiLSTM + Skip-gram
print("\n" + "="*50)
print("EXPERIMENT 4: BiLSTM + Skip-gram")
bilstm_skipgram_model = create_bilstm_model(skipgram_matrix, embedding_dim=200, trainable_embeddings=False)
bilstm_skipgram_results = train_evaluate_lstm(bilstm_skipgram_model, "BiLSTM", "Skip-gram")

# Comprehensive Results Summary for LSTM/BiLSTM Experiments

# Collect all results
lstm_results_summary = [
    {
        'Model': 'LSTM + GloVe',
        'Accuracy': lstm_glove_results['accuracy'],
        'F1-Macro': lstm_glove_results['f1_macro'],
        'F1-Weighted': lstm_glove_results['f1_weighted']
    },
    {
        'Model': 'LSTM + Skip-gram',
        'Accuracy': lstm_skipgram_results['accuracy'],
        'F1-Macro': lstm_skipgram_results['f1_macro'],
        'F1-Weighted': lstm_skipgram_results['f1_weighted']
    },
    {
        'Model': 'BiLSTM + GloVe',
        'Accuracy': bilstm_glove_results['accuracy'],
        'F1-Macro': bilstm_glove_results['f1_macro'],
        'F1-Weighted': bilstm_glove_results['f1_weighted']
    },
    {
        'Model': 'BiLSTM + Skip-gram',
        'Accuracy': bilstm_skipgram_results['accuracy'],
        'F1-Macro': bilstm_skipgram_results['f1_macro'],
        'F1-Weighted': bilstm_skipgram_results['f1_weighted']
    }
]

# Create DataFrame for better visualization
lstm_results_df = pd.DataFrame(lstm_results_summary)
print("\n" + "="*60)
print("LSTM/BiLSTM EXPERIMENTS SUMMARY")
print(lstm_results_df.to_string(index=False, float_format='%.4f'))

# Visualization
plt.figure(figsize=(12, 8))

# Subplot 1: Bar chart comparison
plt.subplot(2, 2, 1)
x = np.arange(len(lstm_results_summary))
width = 0.25

plt.bar(x - width, [r['Accuracy'] for r in lstm_results_summary], width, label='Accuracy', alpha=0.8)
plt.bar(x, [r['F1-Macro'] for r in lstm_results_summary], width, label='F1-Macro', alpha=0.8)
plt.bar(x + width, [r['F1-Weighted'] for r in lstm_results_summary], width, label='F1-Weighted', alpha=0.8)

plt.xlabel('Models')
plt.ylabel('Score')
plt.title('LSTM/BiLSTM Performance Comparison')
plt.xticks(x, [r['Model'] for r in lstm_results_summary], rotation=45, ha='right')
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 2: Accuracy comparison
plt.subplot(2, 2, 2)
plt.bar([r['Model'] for r in lstm_results_summary], [r['Accuracy'] for r in lstm_results_summary],
        color=['skyblue', 'lightgreen', 'salmon', 'gold'])
plt.title('Accuracy Comparison')
plt.ylabel('Accuracy')
plt.xticks(rotation=45, ha='right')
plt.grid(True, alpha=0.3)

# Subplot 3: F1-Macro comparison
plt.subplot(2, 2, 3)
plt.bar([r['Model'] for r in lstm_results_summary], [r['F1-Macro'] for r in lstm_results_summary],
        color=['skyblue', 'lightgreen', 'salmon', 'gold'])
plt.title('F1-Macro Comparison')
plt.ylabel('F1-Macro Score')
plt.xticks(rotation=45, ha='right')
plt.grid(True, alpha=0.3)

# Subplot 4: F1-Weighted comparison
plt.subplot(2, 2, 4)
plt.bar([r['Model'] for r in lstm_results_summary], [r['F1-Weighted'] for r in lstm_results_summary],
        color=['skyblue', 'lightgreen', 'salmon', 'gold'])
plt.title('F1-Weighted Comparison')
plt.ylabel('F1-Weighted Score')
plt.xticks(rotation=45, ha='right')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Find best performing model
best_accuracy = max(lstm_results_summary, key=lambda x: x['Accuracy'])
best_f1_macro = max(lstm_results_summary, key=lambda x: x['F1-Macro'])

print(f"\n Best Accuracy: {best_accuracy['Model']} ({best_accuracy['Accuracy']:.4f})")
print(f" Best F1-Macro: {best_f1_macro['Model']} ({best_f1_macro['F1-Macro']:.4f})")

# Confusion matrices for all models
print("\n" + "="*60)
print("CONFUSION MATRICES")
print("="*60)

models_and_preds = [
    ("LSTM + GloVe", lstm_glove_results['predictions']),
    ("LSTM + Skip-gram", lstm_skipgram_results['predictions']),
    ("BiLSTM + GloVe", bilstm_glove_results['predictions']),
    ("BiLSTM + Skip-gram", bilstm_skipgram_results['predictions'])
]

plt.figure(figsize=(16, 12))
for i, (model_name, predictions) in enumerate(models_and_preds, 1):
    plt.subplot(2, 2, i)
    cm = confusion_matrix(y_test, predictions)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes)
    plt.title(f'{model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('True')

plt.tight_layout()
plt.show()

"""For **LSTM + GloVe**, the model achieves 71.22% accuracy with F1-score (Macro/Weighted) of 70.69%. It benefits from sequential processing and the memory mechanism of LSTMs, which capture temporal dependencies in QA sequences. Pre-trained GloVe embeddings provide solid semantic coverage, but since they are fixed, they sometimes miss domain-specific nuances. Misclassifications are mostly observed between semantically similar classes, especially when vocabulary overlap is high. Overall, LSTM + GloVe performs well but struggles when nuanced, domain-specific context is required.

For **LSTM + Skip-gram**, performance improves to 72.30% accuracy with F1-score (Macro/Weighted) of 71.79%. Skip-gram embeddings capture local context windows and produce more context-aware word vectors, which help the model reduce confusion between related classes. Misclassifications are still present but occur less often than in LSTM + GloVe, especially in categories where subtle word usage matters. Training remains stable and convergence is consistent. This setup proves more effective than GloVe in handling sequential text patterns.

For **BiLSTM + GloVe**, performance decreases slightly by 71.35%. Bidirectional processing captures both past and future context, improving semantic understanding of QA text. The smallerr dense layers 32 tends to effectively handle these richer features. Misclassifications reduce compared to LSTM + GloVe, particularly in classes where forward-only context was insufficient. On average, confusion between overlapping categories drops by 2–3%, showing that bidirectionality helps GloVe embeddings perform slightly better than feed-forward LSTM.

For **BiLSTM + Skip-gram**, the best results supposed to be observed on this model but could not outperform LSTM+skip-gram by 0.08%. Skip-gram embeddings combined with bidirectional layers provide the strongest feature extraction and semantic capture. The model handles nuanced, context-heavy questions more accurately and shows fewer cross-class confusions compared to all other setups. While misclassifications still occur in very close semantic classes, their frequency is the lowest here. This setup consistently outperforms the others in terms of both accuracy and error distribution.

**Overall:**

* Skip-gram embeddings outperform GloVe by reducing misclassifications in context-heavy categories.
* BiLSTM improves over LSTM by lowering confusion in semantically similar classes, thanks to bidirectional context.
* The most stable and effective setup is **BiLSTM + Skip-gram**, which achieves the lowest error overlap and highest accuracy.
* Regularization (dropout=0.3) and tuning (Adam with lr=0.001, 2 LSTM layers) keep training stable and avoid exploding gradients.
"""

# GPU is recommended for training (Runtime → Change runtime type → T4 GPU) # not important
#was implemented to judge the envioremnet

!pip -q install -U tensorflow scikit-learn

import os, numpy as np, tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

print("TF version:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

#extar precausion


glove_matrix= glove_matrix
skipgram_matrix  = skipgram_matrix

# infer basics
max_len = X_train.shape[1]
num_classes = int(np.unique(np.concatenate([y_train, y_val, y_test])).size)
print("max_len:", max_len, "num_classes:", num_classes)

"""Best hyper parameters for Rnn that was tuned through rigours testing:  units=128, dropout=0.2, spatial_dropout=0.2,dense_units=128, lr=1e-3, clipnorm=1.0, embedding_trainable=False.

Available Best hyper parameters for biRnn that was tuned through rigours testing:  units_per_dir=64, dropout=0.2, spatial_dropout=0.2,merge_mode="concat", dense_units=128, lr=1e-3,clipnorm=1.0, embedding_trainable=False

Note: Due hardware limlitation We were limited we were kept units_per_dir=64 instead of 128.
"""

def build_model_rnn(embedding_matrix, max_len, num_classes,
                    units=128, dropout=0.2, spatial_dropout=0.2,
                    dense_units=128, lr=1e-3, clipnorm=1.0, embedding_trainable=False):
    """Vanilla SimpleRNN classifier with frozen pretrained embeddings."""
    vocab_size, embed_dim = embedding_matrix.shape

    inp = layers.Input(shape=(max_len,), dtype="int32")
    x = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim,
                         weights=[embedding_matrix], input_length=max_len,
                         mask_zero=True, trainable=embedding_trainable, name="emb")(inp)
    if spatial_dropout:
        x = layers.SpatialDropout1D(spatial_dropout)(x)

    x = layers.SimpleRNN(units, dropout=dropout, recurrent_dropout=0.0,
                         return_sequences=False)(x)

    if dense_units:
        x = layers.Dense(dense_units, activation="relu")(x)
        x = layers.Dropout(0.3)(x)

    out = layers.Dense(num_classes, activation="softmax", dtype="float32")(x)  # float32 for mixed precision safety
    model = models.Model(inp, out)
    opt = tf.keras.optimizers.Adam(learning_rate=lr, clipnorm=clipnorm)
    model.compile(optimizer=opt, loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model


def build_model_birnn(embedding_matrix, max_len, num_classes,
                      units_per_dir=64, dropout=0.2, spatial_dropout=0.2,
                      merge_mode="concat", dense_units=128, lr=1e-3,
                      clipnorm=1.0, embedding_trainable=False):
    """Vanilla Bidirectional(SimpleRNN) with frozen pretrained embeddings."""
    vocab_size, embed_dim = embedding_matrix.shape

    inp = layers.Input(shape=(max_len,), dtype="int32")
    x = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim,
                         weights=[embedding_matrix], input_length=max_len,
                         mask_zero=True, trainable=embedding_trainable, name="emb")(inp)
    if spatial_dropout:
        x = layers.SpatialDropout1D(spatial_dropout)(x)

    rnn = layers.SimpleRNN(units_per_dir, dropout=dropout, recurrent_dropout=0.0,
                           return_sequences=False)
    x = layers.Bidirectional(rnn, merge_mode=merge_mode)(x)

    if dense_units:
        x = layers.Dense(dense_units, activation="relu")(x)
        x = layers.Dropout(0.3)(x)

    out = layers.Dense(num_classes, activation="softmax", dtype="float32")(x)
    model = models.Model(inp, out)
    opt = tf.keras.optimizers.Adam(learning_rate=lr, clipnorm=clipnorm)
    model.compile(optimizer=opt, loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model
#Analysis by Angshu

'''Best hyper parameters for Rnn that was tuned through rigours testing: units=128, dropout=0.2, spatial_dropout=0.2,dense_units=128, lr=1e-3, clipnorm=1.0, embedding_trainable=False.

Available Best hyper parameters for biRnn that was tuned through rigours testing: units_per_dir=64, dropout=0.2, spatial_dropout=0.2,merge_mode="concat", dense_units=128, lr=1e-3,clipnorm=1.0, embedding_trainable=False

Note: Due hardware limlitation We were limited we were kept units_per_dir=64 instead of 128.'''

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

# ---- which results to plot (left name = pretty label shown on plots, right key = results[...] key) ---
pairs = [
    ("GloVe-200d | SimpleRNN",        "glove_rnn"),
    ("GloVe-200d | BiRNN(SimpleRNN)", "glove_birnn"),
    ("Skip-gram | SimpleRNN",         "skipgram_rnn"),
    ("Skip-gram | BiRNN(SimpleRNN)",  "skipgram_birnn"),
]

# ---- gather metrics and confusion matrices ----
labels   = []
accs     = []
f1s      = []
cms      = {}

for pretty, key in pairs:
    labels.append(pretty)
    pred = results[key]["pred"]
    acc  = results[key].get("acc", accuracy_score(y_test, pred))
    f1   = results[key].get("f1_macro", f1_score(y_test, pred, average="macro"))
    accs.append(acc)
    f1s.append(f1)
    cms[pretty] = confusion_matrix(y_test, pred)

# ---- single grouped barplot: blue = accuracy, orange = macro-F1 ----
x = np.arange(len(labels))
w = 0.38  # bar width

plt.figure(figsize=(10,5))
b1 = plt.bar(x - w/2, accs, width=w, label="Accuracy", color="tab:blue")
b2 = plt.bar(x + w/2, f1s,  width=w, label="Macro F1", color="tab:orange")

plt.xticks(x, labels, rotation=20, ha="right")
plt.ylim(0, 1.0)
plt.ylabel("Score")
plt.title("Accuracy & Macro-F1 by Model")
plt.legend()

# annotate values on bars
def _annotate(bars):
    for bar in bars:
        h = bar.get_height()
        plt.annotate(f"{h:.3f}",
                     xy=(bar.get_x() + bar.get_width()/2, h),
                     xytext=(0, 3), textcoords="offset points",
                     ha="center", va="bottom", fontsize=9)
_annotate(b1); _annotate(b2)

plt.tight_layout()
plt.show()

# ---- confusion matrices with a clearer colormap ----
# choose a perceptually-uniform map; 'magma' has good contrast
for name, cm in cms.items():
    plt.figure(figsize=(6,5))
    im = plt.imshow(cm, interpolation="nearest", cmap="Reds")
    plt.title(f"Confusion Matrix — {name}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    cbar = plt.colorbar(im)

    # annotate counts with readable text color
    vmax = cm.max() if cm.size else 1
    thresh = vmax * 0.6
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            v = cm[i, j]
            txt_color = "white" if v >= thresh else "black"
            plt.text(j, i, f"{v}", ha="center", va="center", color=txt_color, fontsize=8)

    plt.tight_layout()
    plt.show()